services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
  
  web:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    env_file:
      - .env

volumes:
  db_data: